### ISSUE TITLE
你好，你这个播放器可以支持RTMP的直播流么？

### ISSUE THREAD

**Issue by zhang6685979** [sonysuqin/WasmVideoPlayer#1]

**Comment by sonysuqin** [comment]
改改就可以了，我目前是支持MP4/H264，就是封装改一下而已，修改一下代码就行。

zhang6685979 <notifications@github.com> 于2019年3月6日周三 下午5:50写道：

**Comment by zhang6685979** [comment]
能说下具体的解决方案么，刚接触视频这一块  对这个不太了解

**Comment by sonysuqin** [comment]
修正一下之前的说法，你的要求实现起来可能比较复杂，因为FFMpeg实现了RTMP的传输，而放到WASM里，FFMpeg不太可能调到底层的Socket，只能回调到JS来通过Websocket或者HTTP来实现RTMP流的传输，不太建议这么做。用这个播放器来播RTMP有什么意义？是要播H265？

**Comment by zhang6685979** [comment]
对  要播H265

**Comment by sonysuqin** [comment]
如果非要做，建议http+fmp4

**Comment by clwh92** [comment]
有几个问题需要向您请教一下：
1、H265的视频，32位或者64位的都可以吗？通过您提供的视频是可以播放的
2、每次加载新的视频需要重新编译吗？比如说wasm\ffmpeg文件吗？

**Comment by sonysuqin** [comment]
可以，不需要重新编译。 @clwh92
