### ISSUE TITLE
建议作者写一个flv2canvas的项目,现在国内video劫持太严重

### ISSUE THREAD

**Issue by amhoho** [sonysuqin/WasmVideoPlayer#10]
如果想要在移动端浏览器上如直播将视频置于底层就需要对video进行处理,而腾讯UC这些基本都是各种不要脸的对起劫持搞起所谓同层播放器或插播广告.
将视频流解析到canvas播放,目前我看过jsmepg还可以,但是mpeg1-ts来解码实在是效率欠佳,若能将flv或hls解码到canvas播放,这类项目估计会非常火.

**Comment by ouzhou** [comment]
https://juejin.im/post/5d47ddd8e51d4561af16dcb2
