### ISSUE TITLE
rtsp协议 如何支持在线转码播放

### ISSUE THREAD

**Issue by fangkyi03** [sonysuqin/WasmVideoPlayer#11]
rtsp协议 如何支持在线转码播放
ffmpeg我已经编译成功了4.1版本的 但是无法播放在线的 也不知道这么获取在线的帧数据流

**Comment by sonysuqin** [comment]
h5只有websocket可以用，ffmpeg里的socket用不了。

**Comment by fangkyi03** [comment]
现在有个问题是 我是兼容原有的海康视频而不是自己有一个视频直播服务器 我用websocket 也没用

**Comment by sonysuqin** [comment]
在ffmpeg的socket无法使用的情况下播rtsp比较困难，我估计得修改ffmpeg里rtsp里网络相关的实现，变成http或者websocket。
