### ISSUE TITLE
关于moov atom not found 问题

### ISSUE THREAD

**Issue by wenganxiang** [sonysuqin/WasmVideoPlayer#13]
up主好，通过mp4info工具我发现大部分mp4视频的moov信息在最后，所以在decoder在执行openDecoder函数的时候返回的ret是8，本人对c和视频不太熟悉，可否告知如何让moov在末尾的情况下，让ret返回的是0。谢谢

**Comment by sonysuqin** [comment]
最好转一下啊，用ffmpeg一行命令的事，加一个参数-movflags faststart

**Comment by wenganxiang** [comment]
对于没有音频的视频来说是一个很好的解决办法。使用这条命令是可以实现播放了，但是声音会有点卡顿。偶尔会出现如下报错，但是不影响播放。我会照着以下的建议在编译时修改一下编译选项，再看看效果如何。
![image](https://user-images.githubusercontent.com/28584839/66696086-55af2980-ecfb-11e9-8982-4af2205f3f81.png)
