### ISSUE TITLE
decoder.js中的openDecoder参数问题

### ISSUE THREAD

**Issue by wenganxiang** [sonysuqin/WasmVideoPlayer#14]
moov atom not found问题导致了openDecoder函数返回了8。我对视频方面的知识了解的不是很多，我想问一下Decoder.openDecoder中的paramCount和paramSize是什么意思？这两个参数一定要写死吗？

**Comment by wenganxiang** [comment]
用mp4info查看你附件中的mp4文件结构时，刚好第二个数据是moov，而第一个数据ftyp的大小刚好是paramCount * paramSize，这个是巧合吗？

**Comment by sonysuqin** [comment]
那个是巧合，paramCount是传几个参数的意思，paramSize就是每个参数占用的大小，4个字节就是一个int。
