### ISSUE TITLE
Seek 播放怎么实现？能不能给一个思路？

### ISSUE THREAD

**Issue by QianLongGit** [sonysuqin/WasmVideoPlayer#15]
现在急需Seek播放的功能，该怎么实现这个功能，是否可以给个思路，我去尝试一下？

**Comment by sonysuqin** [comment]
抱歉回复晚了，Seek涉及界面、数据获取、缓存、FFmpeg这几个部分，要考虑seek的位置数据已经缓存和未缓存的情况，其实跟普通的播放器里的Seek没有太大区别，只是有一些工作量，最近我可能会找时间把这个功能加进去。
