### ISSUE TITLE
编译代码的时候报错

### ISSUE THREAD

**Issue by wenganxiang** [sonysuqin/WasmVideoPlayer#16]
我下载了ffmpeg3.3，并且和目录同级。
在windows环境下，我使用git bash来运行编译脚本。
报如下错误，：
![image](https://user-images.githubusercontent.com/28584839/66534833-17bed380-eb4a-11e9-97c4-0da193155ec7.png)

![image](https://user-images.githubusercontent.com/28584839/66534408-b34f4480-eb48-11e9-9163-ee80a5ce7458.png)
**在Ubuntu环境下编译时,报如下错误，有一方面的原因可能是emsdk版本的原因（找不到emsdk/fastcomp/fastcomp/bin/lli），我下的是最新版**
![image](https://user-images.githubusercontent.com/28584839/66534780-e80fcb80-eb49-11e9-97c4-791f81ff5777.png)
![image](https://user-images.githubusercontent.com/28584839/66534877-36bd6580-eb4a-11e9-85b8-be276c9951ef.png)

**Comment by sonysuqin** [comment]
Git bash的环境没有试过，可能跟环境有关系，我是在Windows Subsystem for Linux，也就是Ubuntu下执行的。

**Comment by wenganxiang** [comment]
原来是需要在下载完ffmpeg后还要先到ffmpeg目录里执行一次./configure命令生成config.mak和common.mak等文件才能正常执行。建议您可以在README.MD的5.2中加上，以避免有的人忽略了这个步骤，谢谢
@sonysuqin
