### ISSUE TITLE
如果想解码flv视频要从哪里下手？

### ISSUE THREAD

**Issue by wenganxiang** [sonysuqin/WasmVideoPlayer#17]
感谢作者抽空对我之前提问的回答，对您的代码有了更深刻的了解，通过您的代码也对ffmpeg的解码流程有了更清晰的认识 : )
我想问一下，如果要解码flv视频的话，要从哪里下手？应该要改造一下decoder
.c里的openDecoder函数吗？
还有一个问题就是，不论什么格式的视频，解码这一块都不用改了？都是不断的通过XMLHttpRequest获取文件片段然后发送给C端解码就行了？
谢谢。

**Comment by sonysuqin** [comment]
这项目初衷是来播H265编码的mp4，所以FFmpeg编译的Demuxer时候只留下了MP4 Demuxer，Decoder就只留了H265、H264、AAC。FLV就是文件封装换了，在build_decoder.sh配置FFmpeg的语句里加一个--enable-demuxer=flv就可以了，代码不用改。
如果只是文件封装改了，编码都还是AAC、H265、H264的话，就是FFmpeg加入想要的Demuxer就行.
@wenganxiang

**Comment by sonysuqin** [comment]
已经支持。
