### ISSUE TITLE
如果播放直播流的话应该怎么改？

### ISSUE THREAD

**Issue by wenganxiang** [sonysuqin/WasmVideoPlayer#18]
作者实现的是播放本地视频，那如果要播放直播流的话，请问要怎么改比较合适？从代码来看，可能还要对decoder.c做改动？

**Comment by sonysuqin** [comment]
这里并不是本地播放视频啊，虽然数据临时缓存在本地，但还是通过HTTP取到的，直播流的话如果是HTTP+FMP4/FLV都没有问题啊，如果是其他流像RTMP或者RTSP就比较麻烦，因为网络只支持HTTP/WebSocket，总之只要通过HTTP/WebSocket拿到数据，剩下交给FFMpeg就可以。

**Comment by wenganxiang** [comment]
在XMLHttpRequest发起请求后获取到的xhr.len为null，xhr.readyState的值为3，所以一直都在循环执行Downloader.getFileInfo

**Comment by epubcn** [comment]
> 这里并不是本地播放视频啊，虽然数据临时缓存在本地，但还是通过HTTP取到的，直播流的话如果是HTTP+FMP4/FLV都没有问题啊，如果是其他流像RTMP或者RTSP就比较麻烦，因为网络只支持HTTP/WebSocket，总之只要通过HTTP/WebSocket拿到数据，剩下交给FFMpeg就可以。

那就是可以播放http://domain/file.flv这种直播流咯？因为Flash被废除就在眼前，急需一个替代方案。尝试过flv.js、hls.js来播放直播流（hls或flv）都有很多问题（延时大、卡停、黑屏……），不知道您这个是否可应用于稳定播放 hls/flv 直播流的场景呢

**Comment by sonysuqin** [comment]
目前主要是用来点播，用Content-Length来获取文件大小，方便后续Seek，跟这个耦合比较大。要想来做直播的话，这块儿改改吧。不要跟文件大小耦合。

**Comment by sonysuqin** [comment]
已经支持http-flv。
