### ISSUE TITLE
请问这个项目支持fmp4的播放吗？

### ISSUE THREAD

**Issue by zjrwap** [sonysuqin/WasmVideoPlayer#20]
请问这个项目支持fmp4的播放吗？就是Media Source Extension支持的那种fmp4。
如果不支持，是需要重新自己编译ffmpeg吗？谢谢。

**Comment by zjrwap** [comment]
Uncaught abort(18). Build with -s ASSERTIONS=1 for more info.     libffmpeg.js 1 报错

**Comment by sonysuqin** [comment]
fmp4用mse播不就好了。

**Comment by sonysuqin** [comment]
目前播不了，整体都是针对普通mp4做的。为什么要用这个来播fmp4？MSE不就够了？

**Comment by ddcouples** [comment]
> 目前播不了，整体都是针对普通mp4做的。为什么要用这个来播fmp4？MSE不就够了？

MSE无法解码h265

**Comment by sonysuqin** [comment]
目前已经支持http-flv，要支持fmp4的话，ffmpeg需要3.4以上，并且加入--enable-demuxer=dash --enable-libxml2，可以自己试试。
