### ISSUE TITLE
ffmpeg执行 ./configure时报错，shared:ERROR: dist/lib/libavformat.a: No such file or directory ("dist/lib/libavformat.a" was expected to be an input file, based on the commandline arguments provided)，

### ISSUE THREAD

**Issue by BlueBubbleWei** [sonysuqin/WasmVideoPlayer#23]
再执行下面的sh build_decoder_wasm.sh就会有问题，root@DESKTOP-7ME2BST:/home/blue/data/WasmVideoPlayer# sh build_decoder_wasm.sh
Running Emscripten...
shared:ERROR: dist/lib/libavformat.a: No such file or directory ("dist/lib/libavformat.a" was expected to be an input file, based on the commandline arguments provided)
Finished Build

**Comment by bjhanfeng** [comment]
@yyqangular1 我也遇到相同的问题。你解决了嘛？

**Comment by yyqangular1** [comment]
> @yyqangular1 我也遇到相同的问题。你解决了嘛？

还没有，我正在跟emscripten team沟通，你可以可以关注一下
[#9705](https://github.com/emscripten-core/emscripten/issues/9705)

**Comment by bjhanfeng** [comment]
> > @yyqangular1 我也遇到相同的问题。你解决了嘛？
> > 我这边已经通过修改参数暂时可以通过编译，修改 build_decoder.sh如下：
> 
> ```
> emconfigure ./configure --cc="emcc" --cxx="em++" --ar="emar" --ranlib="emranlib" --prefix=$(pwd)/../WasmVideoPlayer/dist --enable-cross-compile --target-os=none \
>         --arch=x86_32 --cpu=generic --enable-gpl --enable-version3 --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter \
>         --disable-programs --disable-logging --disable-everything --enable-avformat --enable-decoder=hevc --enable-decoder=h264 --enable-decoder=aac \
>         --disable-ffplay --disable-ffprobe --disable-ffserver --disable-asm --disable-doc --disable-devices --disable-network --disable-hwaccels \
>         --disable-parsers --disable-bsfs --disable-debug --enable-protocol=file --enable-demuxer=mov --disable-indevs --disable-outdevs
> ```

你用的ffmpeg是什么版本的

**Comment by yyqangular1** [comment]
> > > @yyqangular1 我也遇到相同的问题。你解决了嘛？
> > > 我这边已经通过修改参数暂时可以通过编译，修改 build_decoder.sh如下：
> > 
> > 
> > ```
> > emconfigure ./configure --cc="emcc" --cxx="em++" --ar="emar" --ranlib="emranlib" --prefix=$(pwd)/../WasmVideoPlayer/dist --enable-cross-compile --target-os=none \
> >         --arch=x86_32 --cpu=generic --enable-gpl --enable-version3 --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter \
> >         --disable-programs --disable-logging --disable-everything --enable-avformat --enable-decoder=hevc --enable-decoder=h264 --enable-decoder=aac \
> >         --disable-ffplay --disable-ffprobe --disable-ffserver --disable-asm --disable-doc --disable-devices --disable-network --disable-hwaccels \
> >         --disable-parsers --disable-bsfs --disable-debug --enable-protocol=file --enable-demuxer=mov --disable-indevs --disable-outdevs
> > ```
> 
> 你用的ffmpeg是什么版本的

@bjhanfeng 我的ffmpeg版本3.3.9

**Comment by qiuqiuggt173** [comment]
我再执行build_decoder_wasm.sh时出现下列错误，
wasm-ld: error: 'atomics' feature is used by allformats_fe59c2de.o, so --shared-memory must be used shared
这个怎么改呢

**Comment by tmkmk** [comment]
@yyqangular1 

> > > > @yyqangular1 我也遇到相同的问题。你解决了嘛？
> > > > 我这边已经通过修改参数暂时可以通过编译，修改 build_decoder.sh如下：
> > > 
> > > 
> > > ```
> > > emconfigure ./configure --cc="emcc" --cxx="em++" --ar="emar" --ranlib="emranlib" --prefix=$(pwd)/../WasmVideoPlayer/dist --enable-cross-compile --target-os=none \
> > >         --arch=x86_32 --cpu=generic --enable-gpl --enable-version3 --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter \
> > >         --disable-programs --disable-logging --disable-everything --enable-avformat --enable-decoder=hevc --enable-decoder=h264 --enable-decoder=aac \
> > >         --disable-ffplay --disable-ffprobe --disable-ffserver --disable-asm --disable-doc --disable-devices --disable-network --disable-hwaccels \
> > >         --disable-parsers --disable-bsfs --disable-debug --enable-protocol=file --enable-demuxer=mov --disable-indevs --disable-outdevs
> > > ```
> > 
> > 
> > 你用的ffmpeg是什么版本的
> 
> @bjhanfeng 我的ffmpeg版本3.3.9

我也下载了3.3.9 也使用你的命令.提示 emcc is unable to create an executable file.
这是什么情况啊?

**Comment by yyqangular1** [comment]
> @yyqangular1
> 
> > > > > @yyqangular1 我也遇到相同的问题。你解决了嘛？
> > > > > 我这边已经通过修改参数暂时可以通过编译，修改 build_decoder.sh如下：
> > > > 
> > > > 
> > > > ```
> > > > emconfigure ./configure --cc="emcc" --cxx="em++" --ar="emar" --ranlib="emranlib" --prefix=$(pwd)/../WasmVideoPlayer/dist --enable-cross-compile --target-os=none \
> > > >         --arch=x86_32 --cpu=generic --enable-gpl --enable-version3 --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter \
> > > >         --disable-programs --disable-logging --disable-everything --enable-avformat --enable-decoder=hevc --enable-decoder=h264 --enable-decoder=aac \
> > > >         --disable-ffplay --disable-ffprobe --disable-ffserver --disable-asm --disable-doc --disable-devices --disable-network --disable-hwaccels \
> > > >         --disable-parsers --disable-bsfs --disable-debug --enable-protocol=file --enable-demuxer=mov --disable-indevs --disable-outdevs
> > > > ```
> > > 
> > > 
> > > 你用的ffmpeg是什么版本的
> > 
> > 
> > @bjhanfeng 我的ffmpeg版本3.3.9
> 
> 我也下载了3.3.9 也使用你的命令.提示 emcc is unable to create an executable file.
> 这是什么情况啊?

你这个跟ffmpeg版本没有关系，你的Emscripten环境ok吗？

**Comment by aceip** [comment]
--disable-ffserver 删掉这个 重新编译 可以过去 感觉原因是最新版的ffmpeg设置参数有变化
