### ISSUE TITLE
可以直接使用ffmpeg的io吗？

### ISSUE THREAD

**Issue by pzx601917159** [sonysuqin/WasmVideoPlayer#25]
有几点疑问：
1.不太确定是否可以直接使用ffmpeg的io？
2.当mp4 moov box较大时需要增大waitHeaderLength要设置很大，这个阈值不太好确定。
3.sendData和decoder可以放到不同woker中吗？类似ffplay的逻辑，read/decoder video/audio放在不同线程中。

**Comment by sonysuqin** [comment]
1.不能使用ffmpeg的io，原生的socket目前不支持，目前是用了custom io的方式，通过xmlhttprequest写到缓存，可以考虑加http、websocket等protocol插件，但是要改ffmpeg；
2.这个是我偷懒的做法，应该有更好的办法；
3.我写文档的时候对pthread的支持不够好，目前不知道什么状况，你可以试试，ok的话反馈一下。
