### ISSUE TITLE
请问decoder.js里的 openDecoder方法中 这句含义是什么？

### ISSUE THREAD

**Issue by bondzasd** [sonysuqin/WasmVideoPlayer#26]
请问decoder.js里的 openDecoder方法中
这句含义是什么？
var ret = Module._openDecoder(paramByteBuffer, paramCount, this.videoCallback, this.audioCallback);
    为什么放回0就可以得到正确数据，有的时候返回8 视频播不了。

**Comment by sonysuqin** [comment]
这个是初始化FFmpeg解码器，可能需要读一些数据，如果读不到或者数据不够，可能返回失败哈。
