### ISSUE TITLE
关于参数的一些疑问

### ISSUE THREAD

**Issue by wenganxiang** [sonysuqin/WasmVideoPlayer#27]
你好，我想问一下，里面的一些参数值是怎么考虑的？
1、发送解码命令的周期为什么设为5ms？（按照帧率设置解码周期的话，如30帧设为30ms时会特别卡）
2、每次downlad的数据大小为什么是65536？
3、decoder.c中的kCustomIoBufferSize为什么是32X1024？（设为64X1024也可以正常播放，16没试过）

**Comment by sonysuqin** [comment]
1.按照帧率来的话，加上处理时延，可能来不及，所以处理就是要频率快一些，解码后放缓存里，缓存满就停，缓存不够就重新开始，这样保证流畅播放，也不太耗CPU；
2.这个也是为了考虑速度和CPU的平衡，可以调，请求太大了得等，xmlhttprequest不像native的socket可以返回多少数据读多少数据，他是一次返回所有数据，请求太小的话请求又太频繁；
3.没有什么原因，只是ffmpeg里默认32K，我也给32K，就是影响到读取的频繁程度和内存的分配。
