### ISSUE TITLE
播放flv直播流遇到的问题

### ISSUE THREAD

**Issue by wenganxiang** [sonysuqin/WasmVideoPlayer#29]
你好，我使用ffmpeg命令将视频流推到rtmp服务器上，推流命令如下：
ffmpeg -stream_loop -1 -re -i xxx.flv -c copy -f flv rtmp://xxx/live/12345
然后讲rtmp转成了http-flv转发出去，直播地址为：https://xxxx.com/live/12345
因为直接用xhr播放直播流会有跨域问题，下载这一部分我改了一下，并且申请的cacheBuffer也根据下载到的文件块的大小进行了适配，改了以后播放本地文件是没问题的。
但是播放直播流的时候出现了点问题，我在尝试播放直播流的时候，虽然openDecoder返回了0，但是chrome的控制台提示了“libffmpeg.js:1 [flv @ 0x627f70] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size” 和“libffmpeg.js:1 Consider increasing the value for the 'analyzeduration' and 'probesize' options”的提示，截图如下：
![image](https://user-images.githubusercontent.com/28584839/67821027-8a422400-faf6-11e9-926e-b0905d971812.png)
![image](https://user-images.githubusercontent.com/28584839/67821045-9c23c700-faf6-11e9-83eb-cb38f1d2d152.png)

并且返回的媒体元信息的7个参数也不太正常，截图如下：
![image](https://user-images.githubusercontent.com/28584839/67821127-ddb47200-faf6-11e9-940d-28469921e4bf.png)

可能是因为返回7个媒体元数据参数的不正常，导致了后面在解码的时候提示“[flv @ 0x627f70] Packet mismatch -1665408982 11 84234”
![image](https://user-images.githubusercontent.com/28584839/67821329-98dd0b00-faf7-11e9-84c4-ecfa8adb730f.png)

**Comment by sonysuqin** [comment]
不知道你怎么改的，flv demuxer加进去了吗？播放本地flv有问题？

**Comment by wenganxiang** [comment]
> 不知道你怎么改的，flv demuxer加进去了吗？播放本地flv有问题？

播放本地flv没问题

**Comment by sonysuqin** [comment]
像是元数据有问题，不知道你请求flv的时候，是不是从IDR帧开始的。

**Comment by wenganxiang** [comment]
大概是因为没有用同一套推流/解码的ffmpeg吧，换成同一套ffmpeg以后最起码有画面和声音了。不过还是存在点问题，这部分只能自己改了。谢谢作者的回复 : )

**Comment by yyqangular1** [comment]
> 大概是因为没有用同一套推流/解码的ffmpeg吧，换成同一套ffmpeg以后最起码有画面和声音了。不过还是存在点问题，这部分只能自己改了。谢谢作者的回复 : )

可以在github上分享一下您的修改，大家群策群力。@wenganxiang
