### ISSUE TITLE
用脚本编译时候出现问题

### ISSUE THREAD

**Issue by arkonchen** [sonysuqin/WasmVideoPlayer#31]
1 warning generated.
wasm-ld: error: 'atomics' feature is used by allformats_ea044c9d.o, so --shared-memory must be used

请问之前编译有碰到过这个问题吗

**Comment by sonysuqin** [comment]
没有。估计是版本的问题。

**Comment by yyqangular1** [comment]
> 1 warning generated.
> wasm-ld: error: 'atomics' feature is used by allformats_ea044c9d.o, so --shared-memory must be used
> 
> 请问之前编译有碰到过这个问题吗

这个是wasm的问题，你可以参考[emscripten #8503](https://github.com/emscripten-core/emscripten/issues/8503)寻找一些答案。

**Comment by qiuqiuggt173** [comment]
我也遇到这个问题，你们解决了吗？

**Comment by qiuqiuggt173** [comment]
根据 yyqangular1 c 说的连接，看了一下，Emscripten应该传递--shared-memory给链接器，因为多线程应用程序需要wasm共享内存。
解决办法：编译ffmpeg是把--disable-pthreads加上，去掉线程。但是这样做会对ffmpeg性能有多大影响还未知
我使用的是ffmpeg4.2.1版本最新版
如果大家还有更好的办法，麻烦共享一下，共同学习学习

**Comment by sonysuqin** [comment]
这个代码里根本没有使用pthread，wasm对pthread的支持目前还不成熟。
