### ISSUE TITLE
作者 你好，请教下这里的paramByteBuffer，paramCount具体代表什么意思? 一定要传7和4吗？我传其他数值可以吗？

### ISSUE THREAD

**Issue by zjrwap** [sonysuqin/WasmVideoPlayer#33]
var paramCount = 7, paramSize = 4;
var paramByteBuffer = Module._malloc(paramCount * paramSize);
var ret = Module._openDecoder(paramByteBuffer, paramCount, this.videoCallback, this.audioCallback);
作者 你好，请教下这里的paramByteBuffer，paramCount具体代表什么意思? 一定要传7和4吗？我传其他数值可以吗？

**Comment by sonysuqin** [comment]
那个是从C返回JS的音视频参数个数和每个参数的大小，7就是参数个数，4是参数的大小.
