### ISSUE TITLE
关于播放flv视频的问题

### ISSUE THREAD

**Issue by arkonchen** [sonysuqin/WasmVideoPlayer#34]
我用脚本重新编译了ffmpeg，添加了解码器flv，然后播放的时候，发现解码器能生成，数据无法解析，报Invalid NAL unit size (15205 > 9622)。 是跟decoder.c写的有关系吗，我用vlc能播放这个文件

**Comment by sonysuqin** [comment]
可能是flv的文件格式问题，flv有一些tag并不是标准，但是遵循一些业内的规矩，ffmpeg会从这些tag读元信息、关键帧，我自己的flv倒是可以播放，可以先用同一个版本的ffmpeg、ffplay去试试。
