### ISSUE TITLE
视频音频播放不同步如何调整？

### ISSUE THREAD

**Issue by kongqueyu** [sonysuqin/WasmVideoPlayer#36]
播放过程中 音频会滞后视频，看到文章里提到过是因为内存过高导致，请问如何有办法调整同步吗？如果有的话，如何调整？

**Comment by sonysuqin** [comment]
应该是currentTime的问题，窗口不可见或者网络卡顿的时候没有及时暂停，现在已经做了一些优化，可以试试看还有没有问题。
