### ISSUE TITLE
支持 http-flv 直播

### ISSUE THREAD

**Issue by wangcheng007** [sonysuqin/WasmVideoPlayer#37]
请问如何改成支持直播呢，看到有说改成 环形缓冲区的，前端开发，没有学过 C 研究了两个周末也没研究出来。

其实我觉得可以 通过是否传入 videocallback 和 audiocallback 函数来决定是否是否解码 音/视频，某些场景可能只需要单独一个，比如我。哈哈哈哈哈哈

**Comment by sonysuqin** [comment]
已经支持。
