### ISSUE TITLE
"Assertion failed: Missing signature argument to addFunction" when using the latest emcc (1.39.3)

### ISSUE THREAD

**Issue by ingjieye** [sonysuqin/WasmVideoPlayer#38]

**Comment by ingjieye** [comment]
The document should solved the issue. However a fix to the master branch would be better.
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#calling-javascript-functions-as-function-pointers-from-c

**Comment by sonysuqin** [comment]
Nice.
