### ISSUE TITLE
为什么使用 canvas 进行渲染

### ISSUE THREAD

**Issue by nighca** [sonysuqin/WasmVideoPlayer#4]
请教一下，为什么项目中视频画面的绘制是通过 canvas 来做，而不是将数据转换成浏览器支持的格式（如 H.264），然后喂给 `<video>` 进行播放？

**Comment by sonysuqin** [comment]
这个项目的本来目的是播放H265，H264直接把MP4给video没有问题，但是H265给了播不了啊。

Hanxing Yang <notifications@github.com> 于2019年5月20日周一 下午6:37写道：

**Comment by nighca** [comment]
@sonysuqin 嗯，我明白直接给 H.265 播不了；我是想问，为什么不是把 H.265 内容转换（decode & encode？）成 H.264 然后给 `<video>`？

因为看起来要用 `<canvas>` 绘制视频内容，本身也得做一次 decode？是我哪里理解错误了嘛？

**Comment by sonysuqin** [comment]
你说的方案要把H265解码成YUV，然后YUV编码成H264，给<video>标签后浏览器要再解码成YUV去渲染，没有人会做这么蠢的事情。
得到YUV直接渲染，就是性能最佳的方式。

Hanxing Yang <notifications@github.com> 于2019年6月5日周三 下午6:14写道：

**Comment by nighca** [comment]
@sonysuqin 明白，那主要还是性能的考虑；因为一般情况下支持不支持的格式，常规思路都是转码到支持的格式，然后走原生的播放手段；而用中间产物自己去做渲染，不是常规思路，这是这边我会来问的原因

**Comment by a7a2** [comment]
免费得av1得wasm实现也是基于canvas 进行渲染
详细参考比本项目发布更早得av1 wasm项目：https://github.com/GoogleChromeLabs/wasm-av1
