### ISSUE TITLE
Compile issue with libx264 

### ISSUE THREAD

**Issue by vasanthudhaya** [sonysuqin/WasmVideoPlayer#41]
Hi @sonysuqin i faced an issue when am run the `build_decoder_wasm.sh`. Kindly help me for this issue to resolve. 

`error: asm2wasm seeing an invalid argument type at index 1 (this will not validate) in call from $_file_seek to fined behaviour in C, like defining a function one way and calling it in another, which is important to fix)`

```
Fatal: error in validating output
shared:ERROR: '/home/user/emsdk/fastcomp/bin/asm2wasm libffmpeg.temp.asm.js --total-memory=1073741824 --trap-mode=allow -O3 --mem-init=libffmpeg.js.mem --mem-base=1024 --table-max=-1 --wasm-only -o libffmpeg.wasm --mvp-features' failed (1)
```

**Comment by sonysuqin** [comment]
I don't understand why you need libx264, it should be used in encoder, not in decoder in this player.

**Comment by vasanthudhaya** [comment]
@sonysuqin i wanna decode all types of video. So what can i do for that 

What are the things i need to enable in `ffmpeg configuration`. Kindly let me know....

**Comment by sonysuqin** [comment]
Hard to say how to support "all type of video", because these're too many types. I suggest you list several most used formats.
For example, file formats like "mp4,flv,mkv", then you add specified demuxer, and codec type like "h264,h265,vpx", then you add specified decoder, in build_decoder.sh, it will do the "ffmpeg configuration".

**Comment by vasanthudhaya** [comment]
Thanks for your immediate reply @sonysuqin. I will try and let know you whether is it works for me with the above you mentioned format and demuxer.

**Comment by vasanthudhaya** [comment]
Hi @sonysuqin 

I compiled the ffmpeg with the above you mentioned but i  faced an error while playing the demo 

`libffmpeg.js:1 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ libffmpeg.js:1
libffmpeg.js:1 falling back to ArrayBuffer instantiation
(anonymous) @ libffmpeg.js:1
libffmpeg.js:1 failed to asynchronously prepare wasm: LinkError: WebAssembly.instantiate(): Import #82 module="env" function="b" error: global import must be a number or WebAssembly.Global object
(anonymous) @ libffmpeg.js:1
libffmpeg.js:1 LinkError: WebAssembly.instantiate(): Import #82 module="env" function="b" error: global import must be a number or WebAssembly.Global object
libffmpeg.js:1 LinkError: WebAssembly.instantiate(): Import #82 module="env" function="b" error: global import must be a number or WebAssembly.Global object
abort @ libffmpeg.js:1
decoder.js:1 Uncaught (in promise) abort(LinkError: WebAssembly.instantiate(): Import #82 module="env" function="b" error: global import must be a number or WebAssembly.Global object). Build with -s ASSERTIONS=1 for more info.
common.js:62 [2020-1-11 17:30:35:688][Player][IF] Play video/514754074.mp4.
common.js:62 [2020-1-11 17:30:35:718][Player][IF] Resume.
common.js:62 [2020-1-11 17:30:35:719][Downloader][IF] Getting file size video/514754074.mp4.
common.js:62 [2020-1-11 17:30:35:746][Player][IF] Got file size rsp:200 size:4764487 byte.
common.js:62 [2020-1-11 17:30:35:746][Player][IF] Initializing decoder.
common.js:62 [2020-1-11 17:30:35:747][Decoder][IF] Temp cache req 0.` 

Kindly let me know how to resolve this issue

**Comment by sonysuqin** [comment]
How can I reproduce it?

**Comment by vasanthudhaya** [comment]
@sonysuqin sorry for the late reply. Here is my ff-mpeg configuration.

**Reproduce Steps:**

`emconfigure ./configure --disable-x86asm --disable-inline-asm --disable-doc --disable-stripping --ar=emar --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc --enable-decoder=aac --enable-decoder=_latm --enable-decoder=ac3 --enable-decoder=ac3_fixed --enable-decoder=cook --enable-decoder=h263 --enable-decoder=h263i --enable-decoder=h263p --enable-decoder=h264 --enable-decoder=hevc --enable-decoder=libvpx_vp8 --enable-decoder=libvpx_vp9 --enable-decoder=mjpeg --enable-decoder=mjpegb --enable-decoder=mp2 --enable-decoder=mp2float --enable-decoder=mp3 --enable-decoder=mp3adu --enable-decoder=mp3adufloat --enable-decoder=mp3float --enable-decoder=mp3on4 --enable-decoder=mp3on4float --enable-decoder=mpeg1video --enable-decoder=mpeg2video --enable-decoder=mpeg4 --enable-decoder=mpegvideo --enable-decoder=msmpeg4v1 --enable-decoder=msmpeg4v2 --enable-decoder=msmpeg4v3 --enable-decoder=opus --enable-decoder=pcm_alaw --enable-decoder=pcm_bluray --enable-decoder=pcm_dvd --enable-decoder=pcm_f32be --enable-decoder=pcm_f32le --enable-decoder=pcm_f64be --enable-decoder=pcm_f64le --enable-decoder=pcm_lxf --enable-decoder=pcm_mulaw --enable-decoder=pcm_s16be --enable-decoder=pcm_s16be_planar --enable-decoder=pcm_s16le --enable-decoder=pcm_s16le_planar --enable-decoder=pcm_s24be --enable-decoder=pcm_s24daud --enable-decoder=pcm_s24le --enable-decoder=pcm_s24le_planar --enable-decoder=pcm_s32be --enable-decoder=pcm_s32le --enable-decoder=pcm_s32le_planar --enable-decoder=pcm_s8 --enable-decoder=pcm_s8_planar --enable-decoder=pcm_u16be --enable-decoder=pcm_u16le --enable-decoder=pcm_u24be --enable-decoder=pcm_u24le --enable-decoder=pcm_u32be --enable-decoder=pcm_u32le --enable-decoder=pcm_u8 --enable-decoder=pcm_zork --enable-decoder=ra_144 --enable-decoder=ra_288 --enable-decoder=ralf --enable-decoder=rv10 --enable-decoder=rv20 --enable-decoder=rv30 --enable-decoder=rv40 --enable-decoder=sipr --enable-decoder=vc1 --enable-decoder=vc1image --enable-decoder=vorbis --enable-decoder=vp6 --enable-decoder=vp6a --enable-decoder=vp6f --enable-decoder=wmalossless --enable-decoder=wmapro --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=wmavoice --enable-decoder=wmv1 --enable-decoder=wmv2 --enable-decoder=wmv3 --enable-decoder=wmv3image --enable-decoder=zlib --enable-demuxer=aac --enable-demuxer=ac3 --enable-demuxer=asf --enable-demuxer=avi --enable-demuxer=avisynth --enable-demuxer=flac --enable-demuxer=flv --enable-demuxer=m4v --enable-demuxer=matroska --enable-demuxer=mjpeg --enable-demuxer=mov --enable-demuxer=mp3 --enable-demuxer=mpegps --enable-demuxer=mpegts --enable-demuxer=mpegtsraw --enable-demuxer=mpegvideo  --enable-demuxer=ogg --enable-demuxer=pcm_alaw --enable-demuxer=pcm_f32be --enable-demuxer=pcm_f32le --enable-demuxer=pcm_f64be --enable-demuxer=pcm_f64le --enable-demuxer=pcm_mulaw --enable-demuxer=pcm_s16be --enable-demuxer=pcm_s16le --enable-demuxer=pcm_s24be --enable-demuxer=pcm_s24le --enable-demuxer=pcm_s32be --enable-demuxer=pcm_s32le --enable-demuxer=pcm_s8 --enable-demuxer=pcm_u16be --enable-demuxer=pcm_u16le --enable-demuxer=pcm_u24be --enable-demuxer=pcm_u24le --enable-demuxer=pcm_u32be --enable-demuxer=pcm_u32le --enable-demuxer=pcm_u8 --enable-demuxer=rm --enable-demuxer=vc1 --enable-demuxer=vc1t --enable-muxer=mp3 --enable-muxer=mp4 --enable-muxer=oga --enable-muxer=ogg --enable-muxer=webm --prefix = "$ ( pwd ) /../WasmVideoPlayer/dist"`

After config there will be warning occurs when run the `build_decoder_wasm.sh`. I added the `-s ERROR_ON_UNDEFINED_SYMBOLS=0` then build completed without error. After that i run the demo the above issue (https://github.com/sonysuqin/WasmVideoPlayer/issues/41#issuecomment-573314888) occurs.

**Comment by sonysuqin** [comment]
Can you provide failure file?
