### ISSUE TITLE
如何播放裸流 (H265)？ 

### ISSUE THREAD

**Issue by giter** [sonysuqin/WasmVideoPlayer#42]
目前测试可以通过 `ffmpeg -i video.265  -vcodec copy -f mp4  output.mp4` 转换成mp4并通过VLC播放。但生成的 `output.mp4` 以及 `video.265` 我未找到方法播放

[video.zip](https://github.com/sonysuqin/WasmVideoPlayer/files/4049426/video.zip)

**Comment by sonysuqin** [comment]
目前不支持播放单个Track，需要有音、视频两个Track。
