### ISSUE TITLE
Uncaught RuntimeError: function signature mismatch

### ISSUE THREAD

**Issue by tungct12011** [sonysuqin/WasmVideoPlayer#45]
I built and run it with the following error

![image](https://user-images.githubusercontent.com/44427159/74625721-dc7b8380-517f-11ea-8a10-960a748690db.png)

please support

**Comment by andrewaggb** [comment]
I've been trying this out today for the first time and I had the same problem.  Took me a while to figure it out but after looking at the provided mp4 file vs my files in mp4explorer I noticed the moov atom is first in their file (vs at the end).

you can try to use ffmpeg or gpac to put the moov atom first and then try again.  It worked for me.
eg
ffmpeg.exe -i .\h265_test2.mp4 -movflags faststart -codec copy .\h264_test2_fast.mp4

**Comment by sonysuqin** [comment]
Yes, moov box must be put ahead of mdat box for preparing meta data for FFmpeg so as to "faststart" from network, and audio track is required for now.
