### ISSUE TITLE
Decoder.prototype.openDecoder 返回为7  代表什么错误呢

### ISSUE THREAD

**Issue by erossszh** [sonysuqin/WasmVideoPlayer#5]
![image](https://user-images.githubusercontent.com/40795291/58422238-a7e10c80-80c4-11e9-8a83-cac2edfd8075.png)

**Comment by sonysuqin** [comment]
从代码看，不应该返回7，只会返回0或者8吧，8代表FFmpeg api返回错误。

erossszh <notifications@github.com> 于2019年5月27日周一 下午9:16写道：

**Comment by zhang6685979** [comment]
@sonysuqin 你好，大神，demo中的视频可以播，但是我找的其他H265的视频在解码时返回的都是8，这种问题该怎么解决呢？

**Comment by sonysuqin** [comment]
@zhang6685979 
看看[这个问题](https://github.com/sonysuqin/WasmVideoPlayer/issues/9#issuecomment-517255208)的回答，格式弄成一样的应该就可以了。

**Comment by tablife** [comment]
好的，谢谢，解决了
------------------ 原始邮件 ------------------
发件人: "何震"<notifications@github.com>;
发送时间: 2019年8月15日(星期四) 下午4:09
收件人: "sonysuqin/WasmVideoPlayer"<WasmVideoPlayer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [sonysuqin/WasmVideoPlayer] Decoder.prototype.openDecoder 返回为7  代表什么错误呢 (#5)




@zhang6685979
 看看这个问题的回答，格式弄成一样的应该就可以了。
