### ISSUE TITLE
H265 播放问题

### ISSUE THREAD

**Issue by tablife** [sonysuqin/WasmVideoPlayer#9]
我这里有几个h265/MP4文件都是都放不了。帮忙看下   [文件](https://github.com/tablife/H265.git)

**Comment by StarIsFalling** [comment]
你下载个mp4info，看下包的结构，如果moov在最后，那就需要修改moov的顺序。（或者通过浏览器开发者工具看错误信息，如果提示是moov atom not found就也是这个问题）。最简单的修改可以用ffmpeg:ffmpeg –i input.mp4 –c copy –f mp4 –movflags faststart output.mp4。
这样视频能播，不过音频会杂乱无章对不上

**Comment by fenbitou** [comment]
> 你下载个mp4info，看下包的结构，如果moov在最后，那就需要修改moov的顺序。（或者通过浏览器开发者工具看错误信息，如果提示是moov atom not found就也是这个问题）。最简单的修改可以用ffmpeg:ffmpeg –i input.mp4 –c copy –f mp4 –movflags faststart output.mp4。
> 这样视频能播，不过音频会杂乱无章对不上

这个的确能够处理 moov atom not found 的问题
我这边还测试没有音轨的265视频，似乎都直接返回了 8

**Comment by tablife** [comment]
我们的视频确实没有音轨，能不能处理下，让能播视频， moov顺序 我们自己来处理。



------------------ 原始邮件 ------------------
发件人: "CHANG"<notifications@github.com>; 
发送时间: 2019年8月7日(星期三) 下午5:02
收件人: "sonysuqin/WasmVideoPlayer"<WasmVideoPlayer@noreply.github.com>; 
抄送: "斌"<251448825@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sonysuqin/WasmVideoPlayer] H265 播放问题 (#9)



 
你下载个mp4info，看下包的结构，如果moov在最后，那就需要修改moov的顺序。（或者通过浏览器开发者工具看错误信息，如果提示是moov atom not found就也是这个问题）。最简单的修改可以用ffmpeg:ffmpeg –i input.mp4 –c copy –f mp4 –movflags faststart output.mp4。
 这样视频能播，不过音频会杂乱无章对不上
  
这个的确能够处理 moov atom not found 的问题
 我这边还测试没有音轨的265视频，似乎都直接返回了 8

**Comment by StarIsFalling** [comment]
没有音频流的话，就主要依赖的player.js，decoder.c，decoder.js几个文件里面关于audio和pcmplayer的地方去掉就差不多了
